FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=1000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Copie EN TANT QUE ROOT d'abord
COPY package*.json ./

# PUIS change les permissions ET l'utilisateur
RUN chown -R node:node /app

USER node

# Maintenant npm install marche
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--port", "3000", "--hostname", "0.0.0.0"]