FROM node:18-alpine
WORKDIR /app

# Copie de tous les fichiers nécessaires comme dans le Dockerfile original
COPY package*.json ./
COPY . .

# Installation des dépendances en mode développement
RUN npm install

ENV NODE_ENV development
EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "dev"]