FROM node:18-alpine
WORKDIR /app

# Copie de tous les fichiers nécessaires comme dans le Dockerfile original
COPY package*.json ./
COPY . .

# Installation des dépendances en mode développement
RUN npm install

# Set environment variables
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the Next.js development server
CMD ["npx", "next", "dev"]