FROM node:18-alpine
WORKDIR /app

# Install bash
RUN apk add --no-cache bash

COPY package*.json ./
COPY . .

RUN npm install
RUN chmod +x start-workers.sh

ENV NODE_ENV=development

CMD ["/bin/bash", "./start-workers.sh"]