FROM node:18-alpine
WORKDIR /app

# Install bash and postgresql-client (for psql COPY operations)
RUN apk add --no-cache bash postgresql-client

COPY package*.json ./
COPY . .

RUN npm install
RUN chmod +x start-workers.sh

ENV NODE_ENV=development

CMD ["/bin/bash", "./start-workers.sh"]