create table reconnect_queue (
  id bigint generated by default as identity primary key,
  user_id uuid references next-auth.users not null,
  accounts jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'pending' not null
);

create index idx_reconnect_queue_user_id on reconnect_queue(user_id);